"""Add IssueActivity model for activity tracking

Revision ID: 1d108ef4cdba
Revises: pm6_issue_reviewer
Create Date: 2026-01-02 23:07:37.649692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d108ef4cdba'
down_revision = 'pm6_issue_reviewer'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_activity_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_activity_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_activity_issue_id'))
        batch_op.drop_index(batch_op.f('ix_issue_activity_created_at'))

    op.drop_table('issue_activity')
    # ### end Alembic commands ###
