"""Add Team model and task team assignments

Revision ID: 76a36e71cb1c
Revises: f34a3101bc19
Create Date: 2025-12-28 23:12:26.745628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a36e71cb1c'
down_revision = 'f34a3101bc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Team table
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], name='fk_team_manager_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # Create team_members association table
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_team_lead', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='fk_team_members_team_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_team_members_user_id'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    
    # Add team assignment columns to task table
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewer_team_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_owner_team_id'), ['owner_team_id'], unique=False)
        batch_op.create_foreign_key('fk_task_owner_team_id', 'team', ['owner_team_id'], ['id'])
        batch_op.create_foreign_key('fk_task_reviewer_team_id', 'team', ['reviewer_team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_reviewer_team_id', type_='foreignkey')
        batch_op.drop_constraint('fk_task_owner_team_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_owner_team_id'))
        batch_op.drop_column('reviewer_team_id')
        batch_op.drop_column('owner_team_id')

    op.drop_table('team_members')
    op.drop_table('team')
    # ### end Alembic commands ###
