"""Add archive fields to Task model

Revision ID: b4301e4eea63
Revises: c3d4e5f6g7h8
Create Date: 2025-12-31 11:13:35.780309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4301e4eea63'
down_revision = 'c3d4e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('archive_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_is_archived'), ['is_archived'], unique=False)
        batch_op.create_foreign_key('fk_task_archived_by', 'user', ['archived_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_archived_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_is_archived'))
        batch_op.drop_column('archive_reason')
        batch_op.drop_column('archived_by_id')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
