"""Add multilingual name fields to Team, Entity, TaxType, TaskPreset

Revision ID: bc78eb8f008d
Revises: 76a36e71cb1c
Create Date: 2025-12-29 10:46:38.902837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc78eb8f008d'
down_revision = '76a36e71cb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_de', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('name_en', sa.String(length=200), nullable=True))

    with op.batch_alter_table('task_preset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_de', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('description_de', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))

    with op.batch_alter_table('tax_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_de', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_de', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_de', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_de', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_de')
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_de')

    with op.batch_alter_table('tax_type', schema=None) as batch_op:
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_de')
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_de')

    with op.batch_alter_table('task_preset', schema=None) as batch_op:
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_de')
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_de')

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_de')

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_de')

    # ### end Alembic commands ###
