"""Add multi-stage approval workflow fields

Revision ID: ebe34cad8512
Revises: ff00c7cfda61
Create Date: 2025-12-28 19:17:47.006217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe34cad8512'
down_revision = 'ff00c7cfda61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        # SQLite doesn't enforce foreign keys by default, so we skip FK constraints
        # They are defined in the model and will work in PostgreSQL production

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('rejected_by_id')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('completed_by_id')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('submitted_by_id')
        batch_op.drop_column('approver_id')

    # ### end Alembic commands ###
