"""Add TaskReviewer many-to-many table for multi-reviewer workflow

Revision ID: f34a3101bc19
Revises: 76fd77636f22
Create Date: 2025-12-28 22:47:10.764576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34a3101bc19'
down_revision = '76fd77636f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_reviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('has_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('has_rejected', sa.Boolean(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='fk_task_reviewer_task'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_task_reviewer_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='unique_task_reviewer')
    )
    # Note: Foreign key constraints for existing task columns are already handled by SQLite
    # No batch_alter_table needed as these constraints exist in the model but SQLite doesn't enforce them
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_reviewer')
    # ### end Alembic commands ###
