"""add calendar_token to user model

Revision ID: fd1a6046118a
Revises: fe09fc521814
Create Date: 2025-12-30 23:00:19.571566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1a6046118a'
down_revision = 'fe09fc521814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_calendar_token'), ['calendar_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_calendar_token'))
        batch_op.drop_column('calendar_token')

    # ### end Alembic commands ###
